name: Test

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  action-script:
    name: Action script
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ./test/run-tests.sh
